src/Components/Contact/Contact.jsx, src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx, src/Components/Login/Login.css, src/Components/Login/Login.jsx, src/Components/Navbar/Navbar.jsx, src/Components/Signup/Signup.css, src/Components/Signup/Signup.jsx, src/index.css
Fixed #3 
* CAN YOU LABEL THIS CONTRIBUTION AS A PART OF GSSoC'24 Program
* Padding is added to the footer and is fixed to the bottom.
* The login card (Box) and SignUp card ( Box ) has been centered and box shadow is added to make it clearly visible 
* Navbar was transparent in login and signup page but now the navbar background color changes to blue in the login and signup page. 
* Scrollbar in home page is removed so that the footer contents appears same (in terms of margin, padding)  throughout all the pages.
* Screenshots:
* Footer:
* Login:
5-10 175230](https://github.com/Priyaaa1/StartConnect-Hub/assets/135035523/da14c73c-6d85-4e93-8e93-acfbf5721ddb)
* SignUp:
* No scrollbar
=> Fixed navbar, footer, login and signup

src/Components/About/About.css, src/Components/About/About.jsx, src/Components/Contact/Contact.css, src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx
#9 Issue
Media Queries added.
Now the website can also open in smartphones with a good look!
Screenshots:
@Priyaaa1 
Feel free to review the changes and provide any feedback or suggestions. Thank you!
=> Added Media Queries for improved Mobile Reponsiveness

src/Components/Navbar/Navbar.css, src/index.css
@Priyaaa1 
This is with respect to issue #23 
I have made some changes,
Please review and merge it if applicable.
=> Add Hover effect

src/Components/Testimonials/Testimonials.jsx, src/index.css
Done the required changes regrading testimonials heading #51
=> add testimonials head

package.json, src/Components/Testimonials/Testimonial.css, src/Components/Testimonials/Testimonials.jsx
#9 issue
Hey @Priyaaa1 , I've fixed the mobile responsiveness issue with the new Testimonial feature on the homepage. Everything should look good now!
=> Fix Mobile Responsiveness Issue on Homepage 

src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx
I created and customized this footer with distinct sections. The "footer-content" section includes essential navigation links for seamless exploration, while the "social-media" section enhances engagement by featuring links to various platforms. Each link is adorned with smooth transition effects for a polished user experience, making the footer both functional and visually appealing.
(issue #2 )
=> Enhancement of Footer Effects for Improved User Experience

src/Components/Login/Login.css, src/Components/Signup/Signup.css
=> styling of login and signup button

package-lock.json, package.json, src/App.jsx, src/Components/GoToTop.jsx, src/index.css
Hi @Priyaaa1 ,
This pull request Fixes the issue #59 which I raised regarding the lack of a vertical scroll bar and scroll-to-top button. 
**Changes I made:**
- Added a **vertical scroll bar** (Modified **index.css**).
- Added a **scroll-to-top button** for improved navigation. (Created a new Component **GoToTop.jsx**)
- Used **react icons** (Fa Arrow up)) and **styled components** for go to top button.
These changes will **enhance the usability** and **improve the user experience** of the website.
=> Added a Vertical Scrollbar and Scroll to Top button

src/Components/Hero/Hero.css, src/Components/Navbar/Navbar.jsx
1.The Logo is Linked to the Home Page , when clicked redirects to the home section of the website smoothly
2.Hover Effects are added to the "Explore more" button.
https://github.com/Priyaaa1/StartConnect-Hub/assets/106170225/f533a6ea-468f-4c3a-83c5-526c63f4a2d6
@Priyaaa1 Kindly review this PR
=> Fixes #103 and #110

src/App.css, src/App.jsx, src/Components/About/About.css, src/Components/About/About.jsx, src/Components/Contact/Contact.css, src/Components/FAQ/accordian.css, src/Components/FAQ/accordian.jsx, src/Components/FAQ/data.js, src/Components/Navbar/Navbar.jsx, src/Components/Testimonials/Testimonial.css, src/Components/Title/Title.css
Hello,
This pull request is to fix the issue #38 which was adding an interactive and responsive FAQ section with data relevant to the site.
The FAQ feature is interactive and visually appealing and will highly improve user experience. 
Also, made a small change in the about me section as the heading text was left aligned and paragraph was centered aligned. This misalignment was fixed
=> Adding  FAQ feature

src/Components/Navbar/Navbar.css
- I changed the logo's size to 60px below 800px and changed font size to 14px to make the navbar responsive.
=> Changed the Navbar.css and added few css to make Navbar responsive

src/Components/Testimonials/Testimonial.css, src/Components/Testimonials/Testimonials.jsx
Fixes issue #125 - Testimonial Carousel Navigation Button Positioning Issue
**Summary:**
This pull request addresses and resolves issue #125, which involves the incorrect positioning of the navigation buttons in the testimonial carousel.
**Changes Made:**
=> Fixed the postion of carousel nav button 

README.md
Fixes #135 
This pull request aims to address several minor grammatical errors in the README.md file, such as correcting "Perfom" to "Perform" and "suppose" to "supposed". Additionally, it enhances the specificity of the instructions for committing changes by providing a more detailed example for crafting commit messages. These improvements will enhance the clarity and usability of the contribution guidelines, facilitating smoother collaboration and code maintenance in the StartConnect-Hub project.
=> Update README with improved contribution guidelines

src/Components/ChatAssistant/ChatAssistant.css, src/Components/ChatAssistant/ChatAssistant.jsx
- This PR Enhances the scrollbar look of chatbot.
Fixes #194 
- Cleared all checks.
- Done Default Formetting.
- Visit the chatbot, open it and scroll the text .
=> Enhanced chatbot scrollbar

src/Components/GoToTop.jsx
Hey @Priyaaa1, I have fixed the issue #189 
you can merge it as I have shown feature solution earlier, Thank you.
=> Updated GoToTop.jsx and Reposition the button

src/Components/Footer/Footer.jsx
Hey @Priyaaa1, Fixed issue #157 
i have made the minor changes in footer by adding the link of FAQ section.
=> Added link to "FAQ" in footer

src/App.css, src/App.jsx, src/Components/About/About.css, src/Components/About/About.jsx, src/Components/Contact/Contact.css, src/Components/Contact/Contact.jsx, src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx, src/Components/Hero/Hero.css, src/Components/Hero/Hero.jsx
I changes some code for responsivness. Now this website is responsive upto 300px.
=> Abhisharma1511

src/Components/ChatAssistant/ChatAssistant.css, src/Components/Testimonials/Testimonial.css
Fixed issue of chatbot css in Input Field and added hover effect on images on testimonials.
=> Fixed issue of chatbot css in Input Field and added hover effect.

src/Components/About/About.css, src/Components/Footer/Footer.css, src/Components/Navbar/Navbar.jsx, src/index.css
I have fixed that issue #173 and I raised that issue #174  as well I know it is not assigned but I have to work on that to fix #173. I tested on my side .
=> Fix issue #173

src/Components/Login/Login.css, src/Components/Signup/Signup.css
- This PR  Corrects the outline error of both login and signup Page.
Fixes #196 
- Cleared all checks.
- Done Default Formetting.
- Visit the login and signup page, and click on any input box.
- No outline is shown now.
https://github.com/Priyaaa1/StartConnect-Hub/assets/76861751/02af41b4-67e6-415b-a3fd-1f5beaa64dcd
=> fixes outline error #196

src/App.jsx, src/Components/Footer/Footer.jsx, src/Components/Navbar/Navbar.css, src/Pages/HowItWorks.jsx, src/Pages/PrivacyPolicy.jsx, src/Pages/TermsAndConditions.jsx, src/Pages/VisionAndMission.jsx
Hey @Priyaaa1 I've added the dedicated pages for "How it Works, Vision & Mission, Privacy Policy and Terms & Conditions" to the Website.
Please take a look and review it, 
Thank you for the opportunity to contribute in your project.
=> Added "How it Works, Vision & Mission, Privacy Policy and Terms & Conditions" Pages to the Website

src/Components/FAQ/accordian.css, src/Components/FAQ/accordian.jsx
**This PR enhances the FAQ section by introducing two main improvements:**
1. **Smooth Scroll Effect:** Implemented smooth scrolling when an FAQ question is clicked, providing a better user experience.
2. **Rotating Arrow Icon:** Added a rotating effect to the arrow icon beside each FAQ question to indicate whether the answer is expanded or collapsed.
**Fixes:** #214
**Implementation Details**:
- Utilized useRef and useEffect hooks to dynamically calculate the content height and apply smooth scrolling.
- Applied CSS transitions for smooth opening and closing of FAQ answers.
- The arrow icon rotates smoothly to indicate the open or close state.
**Changes Made:**
- Added dynamic content height calculation using useRef and useEffect.
- Implemented smooth transitions for FAQ answers using CSS …
=> Enhanced FAQ section with icons and smooth scrolling

README.md
=> Adding a README file, Installation and Setup Guide

index.html
Added some important meta tags in HTML file that enhance the SEO of the website.
Issue Number:
Fixes issue #218 
Other information:
#How has this been tested ?
Testing using Google Lighthouse.
=> Added meta elements that enhance SEO performance

src/Components/Footer/Footer.jsx
Hi,
I have changed the logo of X(Twitter) which was assigned to me.
Issue #223 
Could you please add level to it.
Thanks
=> modified:   Change the twitter logo to latest one

package-lock.json, package.json, src/App.jsx, src/Components/About/About.jsx, src/Components/FAQ/accordian.jsx, src/Components/Footer/Components/AboutUS.jsx, src/Components/Footer/Components/Main.css, src/Components/Footer/Components/contact.jsx, src/Components/Footer/Components/data.js, src/Components/Footer/Components/faq.jsx, src/Components/Footer/Footer.jsx, src/Components/Hero/Hero.jsx, src/Components/Testimonials/Testimonials.jsx
I have created the components for the About Us, Contact Us and Faq section of the footer section of the website 
Now it is like this
=> Added UI of the About Us, Contact Us and Faq section of the footer section of the website 

src/Components/Footer/Footer.jsx
Now the year will be synced automatically
=> Edited Dynamic code for year

src/Components/ChatBot/ActionProvider.jsx, src/Components/ChatBot/MessageParser.jsx
Fix Issue : #263 
The ChatBot is designed to provide responses only to questions it has been programmed to recognize. To address this limitation, I have improved its functionality by adding a default response for unknown questions. Additionally, users now have the option to ask the bot to suggest questions when they do not have any specific inquiries. This enhancement aims to make the interaction with the ChatBot more user-friendly and informative.
Before : 
After : 
Resolved issue #263
=> Fix: Issue(#263) Bug At chatbot 

src/App.jsx, src/Components/Footer/Footer.jsx
Terms and Condition, Privacy Policy and Vison and Mission Pages in the footer are now linked
Fixes ISSUE : #286 
@Priyaaa1 Kindly review
=> Added Links to the Footer Pages

src/App.jsx, src/Components/Footer/Footer.jsx
Reverts Priyaaa1/StartConnect-Hub#313
=> Revert "Added Links to the Footer Pages"

package-lock.json, src/Components/Testimonials/Testimonial.css, src/Components/Testimonials/Testimonials.jsx
fixed issue no #150 #146 
https://github.com/Priyaaa1/StartConnect-Hub/assets/113816862/0cba3f0e-46f8-478a-911c-32f31c4de268
=> Added new hover effect in testimonials section

src/Components/ChatAssistant/ChatAssistant.css, src/Components/ChatBot/config.jsx
#279 Feat/ChatBot ui is not good resolved on clicking it works properly
fixes #279 
under gssoc'24
click on chat box it closes and open on clicking the chatbot avatar
https://github.com/Priyaaa1/StartConnect-Hub/assets/116994649/96329760-7ee8-4ce4-a927-c686816bd57e
=> ui of chatbox is enhanced #279

src/Components/Footer/Footer.jsx
Terms and Condition, Privacy Policy and Vison and Mission Pages in the footer are now linked
@Priyaaa1 this is the new PR of the previously mentioned issue , Kindly review
=> AddedPage Links in Footer Section

src/Components/Footer/Footer.css, src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx
Made Navbar disappear on scrolling upward and reappear on scrolling downward.
Issue #303
=> Made Navbar Disappear on Scrolling

package-lock.json, src/Components/Navbar/Navbar.css
I have added the navbar animation for mobile devices
fixed #191 
https://github.com/Priyaaa1/StartConnect-Hub/assets/83546205/b7f19550-cc2c-425d-b9dc-8cd8e1990bff
=> navdropdown animation added

src/Components/ChatBot/ActionProvider.jsx, src/Components/ChatBot/MessageParser.jsx
I have added a lot many functions which address many new keywords now about experience, location, thank you, more details, services , pricing etc. and added new keywords to existing ones so that chat bot is able to answer more question.
This Fixes #293
=> GSSOC: ChatBot updates (Fixes #293)

netlify.toml, package.json
Hey @Priyaaa1 I have solved the page not found error for the pages, Issue closes #264 
With the right rewrite and redirect rules, we can ensure that all requests are redirected to the root URL, preventing the page not found error from occurring.
I have created a `netlify.toml` file to configure rewrite and redirect rules:
In the above code, we defined a simple rewrite rule:
- `[[redirects]]` defines a section for specifying redirects and rewrites. It's a Netlify-specific configuration that allows you to control how the server handles incoming requests.
- `from = "/*"` defines the pattern for matching incoming requests. In this case, /* matches any path requested on your deployed site.
- `to = "/index.html"` specifies the target destination for all the matched requests. It tells the server …
=> Resolved "Netlify Routing Navigation Errors" For The Pages 

src/Components/Login/Login.css, src/Components/Login/Login.jsx
**Actual Behaviour:**
Even though When the user does not enter any details in the login form it works and it will go to the View Our Services page
**Expected Behaviour:**
I added input label message text "Please Enter Email" and "Please Enter Password" on the Login page for user-friendly and user can't login without fill the input values on login page
issue No: #311
https://github.com/Priyaaa1/StartConnect-Hub/assets/121508628/245991be-2f9b-4eef-ae61-fd3f22f37722
**If it's not good, please assign me again I will do it better**
=> [BUG]: Login Button

package-lock.json, package.json, src/App.css, src/App.jsx, src/Components/About/About.css, src/Components/About/About.jsx, src/Components/Contact/Contact.css, src/Components/Contact/Contact.jsx, src/Components/Footer/Footer.css, src/Components/Navbar/Navbar.jsx
Resolved issue #213 
@Priyaaa1 Now the issue is resolved and I have updated it mam. Can you please check once and let me know if any changes are required?
=> Added Dark Mode Toggle

src/Components/Testimonials/Testimonial.css, src/Components/Testimonials/Testimonials.jsx
Image alignment in testimonials
#265
=> #265 image-placement fixed in testimonials

src/Pages/Explore.css, src/Pages/Explore.jsx
=> made service now page responsive

src/Pages/PrivacyPolicy.jsx, src/Pages/TermsAndConditions.jsx, src/Pages/VisionAndMission.jsx
Solved Issue #334  Now the pages - Terms and Conditions , Privacy Policy & Mission and Vision opens at the top when the respective routes are hit.
https://github.com/Priyaaa1/StartConnect-Hub/assets/154724111/b4471bdf-4dd5-44c5-9fce-80055fba4260
=> Solved the issue of page rendering at bottom

README.md
=> Addition of Contributprs logo's and no of forkd pr issue stars count in Readme.md

src/Components/Footer/Footer.jsx
=> Updated Footer.jsx

src/Components/Footer/Footer.jsx
=> Updated collaboration link

src/App.jsx
hi @Priyaaa1 ,
issue closes #366 
I have resolved the issue to persist the dark mode preference across page refreshes using localStorage.
The changes ensure that the user's selected mode (dark or light) is maintained even after the page is refreshed.
=> Resolved Dark Mode Persistance Issue After refreshing

src/Components/Login/Login.jsx, src/Components/Signup/Signup.css, src/Components/Signup/Signup.jsx
Issue no:- #360 
Added form validation in Login and signup page
=> Added validation in form

src/Components/Footer/Footer.jsx
=> Added the github icon

package-lock.json, package.json, src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx
Issue no: #385 
I have updated the toggle switch UI and now it looks much better.
I have also added the text "change theme" on hovering the toggle switch.
Before:
After:
@Priyaaa1 please review this PR and merge it with main.
Thank you.
=> Updated toggle switch of light/dark mode

.github/ISSUE_TEMPLATE/pull_request_template.md
As mentioned in Issue No: #412 , I have added a PR template and made the issue no and description as compulsory. 
@Priyaaa1 please review this and merge it with main. 
Thank You. 
Fixes: #412
=> Feat: Added a PR template

package-lock.json, package.json, src/App.jsx, src/Components/Testimonials/Testimonials.jsx
=> Resolving Conflict and Refactoring

package-lock.json, package.json, src/App.jsx, src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx
Resolved issue https://github.com/Priyaaa1/StartConnect-Hub/issues/364
@Priyaaa1 I added the Let's Connect Section
=> Updated Footer

.github/workflows/auto-comment-pr-merge.yml
=> Auto Commenting when a PR is merged 

.github/ISSUE_TEMPLATE/documentation.md
=> Added issues template for documentation issues

package-lock.json, package.json, src/App.css, src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx, src/index.css
Closes #332 
https://github.com/Priyaaa1/StartConnect-Hub/assets/120386924/87d0f3c3-b1ec-422b-80f5-97c2fa7e6b7d
Hey! @Priyaaa1 
I have successfully added hover effects to the header; please check and let me know if you need any other customizations.
Regards,
Tanishka
=> Added hover effect in Header

src/Pages/Explore.css, src/Pages/Explore.jsx
=> Fixed the outline issue and centered  Know more

src/Components/Footer/Footer.jsx
=> Replace Twitter with X

src/Components/Footer/Footer.jsx, src/Pages/HowItWorks.jsx
Hey @Priyaaa1,
issue closes #465 
I have added the **How it works page** in the footer section's "Need Help" Section and also the Link to the respective page. Also I have added scroll to top on the respective page when the link is clicked.
As you can see below - 
https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/4b376c04-f9a1-47ee-97fe-84c6d93eaacf
=> Added Link to "How it Works" Page

src/Components/Login/Login.jsx, src/Pages/Explore.css, src/Pages/Explore.jsx
Solved issue #438 
[2ffe186e-62d6-407a-adc6-030fd5e5fc3b.webm](https://github.com/Priyaaa1/StartConnect-Hub/assets/154724111/64b75d5b-015f-4a81-bacf-34880498f03b)
=> Fixed the email validation bug and added a check for empty pw field

package-lock.json, package.json, src/App.jsx, src/Components/Footer/Footer.jsx, src/Components/Navbar/Navbar.jsx, src/Pages/FeedbackForm.jsx, src/Pages/feedback.css
Hey @Priyaaa1 
I have updated the feeback form with the new email.
Please take a look and review it, Thank You!!
=> Added Revert Updated "Feedback Form"

src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx
Solves 
Issue no: #443 
I have created a responsive footer section that adapts seamlessly to different screen layouts, ensuring optimal spacing, alignment, and visibility of content and social media icons. The footer section dynamically adjusts its layout and styling based on the screen size. On larger screens, such as laptops and desktops, the footer sections are neatly organized in a horizontal layout, with appropriate spacing and alignment. As the screen size decreases, the sections gracefully stack vertically, preventing content overlap and ensuring readability.
Screenshots-
Before:
After:
=> Solved footer alignment issue and made it responsive

package-lock.json, src/Components/Footer/Footer.css
Hey @Priyaaa1 issue closes #483 
i have added Hover Effect to Footer Content and Links
https://github.com/Priyaaa1/StartConnect-Hub/assets/163530398/3c555f67-76be-4fb4-8905-2314f987e837
Please take a look and review it, Thank You
=> Added "Hover Effect" to "Footer" Content and Links

src/App.jsx, src/Components/Footer/Footer.jsx, src/Components/Navbar/Navbar.jsx, src/Pages/FeedbackForm.jsx, src/Pages/feedback.css
Hi @Priyaaa1  #444 
I have made the changes and push the files without pushing other dependencies to ensure Branch conflicts please try to merge this PR Before any other PRs and see if it is working properly.
=> Updated "Feedback Form"

src/Components/Login/Login.jsx
Fixes the merge conflict of #503 and issue #340 
My earlier PR #503 had some merge conflicts that needed to be resolved. However i had already deleted the folder from my PC thereby am unable to revert back to the commit changes even after git reset --hard. So i have opened this new PR with the same changes. Kindly accept and merge this one and follow the requisites steps mentioned in the earlier PR and close the earlier PR. I am not closing the earlier PR #503  now because you might need to reference from it for the OAuth client steps.
Thanks for understanding.
=> Resolved the google login functionality Fixes the merge conflict of #503 and issue #340

src/Components/Login/Login.css
Adujsted the padding and margin to have a uniform look in full as well as Mobile screen.
issue no: #509
=> Fixed login page for mobile screen

src/Pages/FeedbackForm.jsx
Hey @Priyaaa1,
issue closes #518 
**Issue Description**
The feedback form on the website did not reset after submission, leaving the input fields populated with the user's data.
**Fix Implemented**
- Added functionality to reset the form fields after successful submission.
- Ensured a clear indication of form submission and prepared the form for new entries.
Here as you can see - 
https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/fe7b0d89-1f24-48d9-b3ab-7e0c9c3efa4e
=> Added Reset functionality in feedback form

src/Pages/FeedbackForm.jsx, src/Pages/feedback.css
=> Made the page responsive

src/App.jsx, src/Components/ProgressBar.jsx, src/Components/progressbar.css, src/index.css
Hey @priyaaa1 | Issue Closes #446 
I have added the Scroll Down Progress Bar to the website
https://github.com/Priyaaa1/StartConnect-Hub/assets/101971980/34f332f5-ec81-48dc-931f-b47822f6d645
Please take a look and review it, Thank You!
(**NOTE**: As there are so many transitions and animations at the Home Page the Bar might look like as not working kindly navigate to other pages and review it!! )
=> Added "Scroll Down Progress bar" to the Website

src/Components/Footer/Footer.jsx, src/Components/Navbar/Navbar.jsx
Solved issue #536 
https://github.com/Priyaaa1/StartConnect-Hub/assets/154724111/9ae4592f-522a-4535-8451-da95495a53be
=> Fixed the bug

src/Pages/HowItWorks.jsx, src/Pages/PrivacyPolicy.jsx, src/Pages/TermsAndConditions.jsx
Hi @Priyaaa1 | Issue closes #527
I have added "Proper Alignments" for "Pages Contents" 
Please take a look and review it, Thank You!!
=> Added "Proper Alignments" for "Pages Contents" 

src/Components/Footer/Footer.jsx
The twitter icon used was the old one, I changed the twitter icon to the new one.
=> Changed twitter icon

src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx, src/Components/Preloader/Preloader.jsx, src/Components/Signup/Signup.css, src/Components/Testimonials/Testimonial.css, src/Components/Testimonials/Testimonials.jsx
1. **Fixed Issues Issues of Nav Bar :** Made the navbar sticky and changed theme for better navigation and User Experience 
2. **Fixed Login and Sign up :** fixed the alignment of login and signup cards respectively.
3. **Testimonial Readability Enhanced** : Enhanced the Testimonial cards text readability by changing the font color to white on hover .
P:S:Kindly Review and merge the PR in the main , and mark and label this under GSSOC 24
=> Nav Bar Sticky feature , Login and sign form Alignment and Testimonial Readability fixed 

src/Pages/FeedbackForm.jsx, src/Pages/feedback.css
Hey @Priyaaa1,
issue closes #546 
I have implemented the pop up message after submitting the feedback form.
What i did - 
1. I **added the pop up notification** after submitting the feedback form
2. **added "pop-up close"** button at the top to close the popup notification
3. **added "Back to Home" button** to easily redirect to the home page after submitting the form.
4. also, i **tried my very best to match the color theme** of the website
as you can see - 
Please take a look -
https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/52c8b000-9108-430b-9769-a38e1610839a
Please let me know if there's anything that need to be improve.
Thankyou!
=> Implemented "Submitted Confirmation"  Pop-Up in Feedback Form

src/Components/Hero/Hero.css, src/Pages/Explore.css
Increased the speed of the transition on the home page making it look more smoother by decreasing the in and out coincide time of the images.(Issue number #532)
Changed the colours that appear during the hover when the cursor is brought onto the cards on services page,this helped in making the texts inside the cards visible.(Issue number #530)
Both the issues have been fixed in this pull request please review them both.
=> Improved transition and Fixed texts not being visible when hovered on cards

package-lock.json, src/App.jsx, src/Components/Footer/Footer.jsx, src/Pages/Blogs.jsx, src/index.css
Fixes issue #566 
. Contains blog tags
. Blog search
=> Added blog page

package-lock.json, package.json, src/Pages/FeedbackForm.jsx
Hey @Priyaaa1 ,
issue closes #569 
I have updated all the ID's **("Service_ID", "Template_ID", and "User_ID")** to your credentials.
**Here is the DEMO** - (if you have received the below feedback on the email-id, Then **functionality is working fine**.)
https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/c8ed5a46-fc34-4b44-bbf3-567f90ea7ee1
Thankyou for coordinating!
Please take a look
=> Implemented Real Email Functionality

package-lock.json, src/Components/Navbar/Navbar.css
This PR addresses the issue of number #46 which states 'Change hover of navbar' enhancing the navbar by introducing subtle yet impactful improvements to its interaction and appearance. While most of the major changes have already been implemented by other contributors and repo maintainers, this PR focuses on refining the user experience with the following updates:
1. **Hover Effect Enhancement**:
- Increased the font size of navbar options when hovered upon.
- Added an underline to the text being hovered to improve visual feedback.
- **CSS Modifications**:
- Adjusted the hover state for navbar links to increase font size and add an underline.
- Ensured smooth transitions to enhance the overall user experience.
These changes aim to improve the visual aesthetics and interactivity of the …
=> Change hover of navbar.. (#46)

src/Components/Footer/Components/Visitors.jsx, src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx
=> Feat: In footer logo,visitors count and star us button added

package-lock.json, package.json, src/Components/Contact/Contact.jsx
Added an email address box in the contact form. Also added the functionality of email check with a proper error message.
issue no #273
=> Fix issue #273 email box with validation 

src/Components/Footer/Footer.css
=> Bug: footer anchor tag fixed

src/App.jsx, src/Components/Footer/Footer.jsx, src/Pages/Contributors.css, src/Pages/Contributors.jsx
Solved issue #582 
https://github.com/Priyaaa1/StartConnect-Hub/assets/154724111/d7aa5587-6516-42d7-b05c-f0fa179e5b50
=> Added the contributors page

package-lock.json, package.json, src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx, src/index.css
https://github.com/Priyaaa1/StartConnect-Hub/assets/59639410/c320685f-9792-434e-b5af-c055c72618de
=> Hamburger icon needs to replace with close icon after menu opens #542

src/App.css, src/App.jsx, src/Components/About/About.jsx, src/Components/Contact/Contact.jsx
solved issue dark mode and light mode
video:
https://github.com/Priyaaa1/StartConnect-Hub/assets/115735153/ff65e17a-cc50-4ed1-8f98-cd5f04471d93
I'm a GSSOC Contributor.
=> solved issue dark mode and light mode

src/Pages/Contributors.css, src/Pages/Contributors.jsx
Hey @Priyaaa1 issue closes #611 
I have Made "Our Contributors" Page responsive and Align
=> Made "Our Contributors" Page responsive and Align

src/Components/Footer/Footer.css, src/Components/GoToTop.jsx
=> Top to bottom icon hides footer #545

src/Components/Navbar/Navbar.css, src/Components/Navbar/Navbar.jsx
Hey @Priyaaa1 
- Issue closes #594 
I have fixed the issues when we get after hovering the nav links and logo or title.
Additionally, I have added new hover effects and made some changes. 
https://github.com/user-attachments/assets/0f6211d9-7c61-4202-b251-7e7c45c0fccf
Please take a look and review it, Thank You!!
=> Fixed BUG: Navbar Alignment issues while hovering

index.html
issue:- To Add Multilingual feature of Google Translate. #632
Added the feature multilingual translation.
=> Google Translator

src/Components/FAQ/data.js
Hey @Priyaaa1 ,
closes issue #628 
I have expanded the FAQ section 
**Please take a look and review it**
******Screenshot/video******
https://github.com/user-attachments/assets/b21ae761-c066-43d1-b2a1-d2f1b744f80e
=> Expanded the FAQ section

src/Components/FAQ/accordian.css
=> add hover on faq section cards

src/Components/ChatAssistant/ChatAssistant.css, src/Components/ChatBot/ActionProvider.jsx, src/Components/ChatBot/MessageParser.jsx, src/Components/ChatBot/Options.jsx, src/Components/ChatBot/config.jsx, src/Components/ChatBot/utils.jsx
Hey @Priyaaa1 
- Issue Fixes #613
I have added the guided functionality to the chatbot with predefined options and action handles
**Files Changed:**
- `ActionProvider.jsx`
- `MessageParser.jsx`
- `config.jsx`
- `ChatAssistant.css`
**Files Created:**
- `Options.jsx`
- `utils.jsx`
**Changes I made:**
- Made changes in `ActionProvider.jsx`, Added new action handlers for `Options` `handleHell`, `handleThank`, `defaultResponse`.
- Updated existing action handlers for improved functionality.
- `MessageParser.jsx`: Enhanced message parsing logic for specific user queries.
- Fixed issues with default responses and handling of gratitude messages.
- Created `Options.jsx` and added dedicated predefined options
- `config.jsx` Updated configuration to integrate new actions and ensure compatibility …
=> Added "Guided Conversation" Functionality to the Chatbot 

src/App.jsx, src/Pages/Blogs.jsx, src/Pages/Contributors.css, src/Pages/Contributors.jsx, src/Pages/Licensing.jsx, src/Pages/feedback.css
Hey @MastanSayyad
I have made the changes and fixed the dark mode working
I have Fixed:
-  Dark Mode Functionality
-  Licensing Page
-  Our Contributors Page
-  Feedback Page
-  Blogs Page
issue fixes #650 
Please take a look and review it
=> Fixed the Dark Mode is Working and Enhanced the Contributors Page and Other Pages

src/Components/FAQ/accordian.css, src/Components/FAQ/accordian.jsx, src/Components/Footer/Components/faq.jsx
Fixed the FAQ section
Required Fixes #621 
[x] Bug fix
Before:
After:
[x] I have made this change from my own.
[x] I have taken help from some online resources.
[x] My code follows the style guidelines of this project.
[x] I have performed a self-review of my own code.
[x] My changes generate no new warnings.
[x] I have tested the changes thoroughly before submitting this pull request.
[x] I have provided relevant issue numbers and screenshots after making the changes.
=> enhanced faq section

package-lock.json, package.json, src/Components/Contact/Contact.css, src/Components/Contact/Contact.jsx
#631 
completed 
Also Added on error message if there is spam .
=> contact us notification

src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx
This pull request adds a newsletter subscription form to the footer of the website. The form allows users to enter their email addresses and subscribe to updates. The section is integrated with the existing footer design, ensuring a seamless appearance.
Please review this changes and approve
fixes issue https://github.com/Priyaaa1/StartConnect-Hub/issues/630
- Closes #630
**Before**
**After**
Adding a newsletter subscription form to the footer enhances user engagement by providing an easy way for visitors to subscribe to updates. It helps in building a subscriber base and keeping users informed about the latest news and updates.
Please review the changes and provide feedback. Thank you!
=> Add Subscription Form to Footer

src/Components/Footer/Footer.css
=> Fixed footer for all screen sizes

src/Components/GoToTop.jsx, src/index.css
Hey @MastanSayyad 
- issue closes #673 
I have enhanced the scroll to top button and re-style vertical scroll bar.
Changes Made:
-  Added transition: transform 0.3s ease, background-color 0.3s ease; to the Wrapper for smooth transitions on hover.
-  Applied transform: scale(1.1); on hover to slightly zoom in the button.
-  Added a transition to the .top-btn--icon for smooth transformation of the arrow.
-  Applied transform: translateY(-2px); on hover to slightly move the arrow up.
-  Replaced FaArrowUp with FaChevronsUp from react-icons/fa.
-  Restyle the vertical scroll bar
=> Enhanced the Scroll to Top Button and Re-Style the Vertical Scroll Bar

src/Components/Footer/Footer.css, src/Components/Footer/Footer.jsx
Hello Project Admin
I Added Icons to Footer Links - Solved #668 
Kindly Please go through this PR @MastanSayyad
=> Added Icons to Footer Links

src/Pages/Licensing.jsx, src/Pages/PrivacyPolicy.jsx, src/Pages/TermsAndConditions.jsx
[Please include a brief description of the changes or features added]
fixed static year/date bugs in three files policy, t&c, licensing and fixed earlier footer copyright issue already. in #664 
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #672 
[Attach any relevant screenshots or videos demonstrating the changes]
[Include any additional information or context that might be helpful for reviewers.]
=> Fixed #672

src/Components/Login/Login.css, src/Components/Signup/Signup.css
I have properly aligned the Google Login button, as well as i have also implemented proper spacing in SignUp component ( Added some margin between signup with google button and text )
- Closes #694 
Old login page :
New Login Page : 
Old SignUp Page : 
New SignUp Page : 
Thanks for assigning this issue to me
=> Fixed google login button issue and tweeked signup component UI

src/Components/Signup/Signup.css, src/Pages/Contributors.jsx
Hey @MastanSayyad 
- issue closes #704 
I have fixed the bug in contributors data fetching in the contributors page and I also fixed the dark mode functionality in sign up page
https://github.com/user-attachments/assets/45f0b3fb-f156-4eca-b5fa-c4f34779e6e1
=> Fixed the Bug in Contributors Data Fetching in Contributors Page

src/Components/Navbar/Navbar.css
fixes #689 
- Closes #689 
- [x ] Bug fix
- [x ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x ] I have updated my branch and synced it with project `main` branch before making this PR
- [x ] I have performed a self-review of my code
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.
=> Improved the theme button in Navbar

src/Components/Navbar/Navbar.jsx
Hey @MastanSayyad 
- issue closes #709 
I have added the icons to the navbar links
Please take a look and merge it
=> Added Icons to Navbar Links

src/Components/Contact/Contact.css, src/Components/Contact/Contact.jsx
validation needs to be done on phone number #676
None
- Closes #676 
https://github.com/user-attachments/assets/ebfdc456-f5c5-4071-893e-43f2e7419062
[Include any additional information or context that might be helpful for reviewers.]
=> validation needs to be done on phone number #676

src/App.jsx, src/Components/CookiePolicy/CookieConsent.css, src/Components/CookiePolicy/CookieConsent.jsx
Hey @MastanSayyad @Priyaaa1 
issue closes #713 
I have created a custom cookie consent popup in the website 
- followed the website theme
- made sure it applies to both light and dark mode
- made sure it doesn't overlap with the scroll to top button 
- added "learn more" button to redirect user to the privacypolicy page
- on clicking accept cookies, popup will be hidden.
Here -
https://github.com/user-attachments/assets/be599062-215e-4180-b414-5b47925be203
[Include any additional information or context that might be helpful for reviewers.]
=> ✔️Added Cookie popup to StarConnect!

src/Components/About/About.css, src/index.css
Fixed the responsive of about section cards for all screen sizes
[Please include a brief description of the changes or features added]
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #718 
[Attach any relevant screenshots or videos demonstrating the changes]
[Include any additional information or context that might be helpful for reviewers.]
=> Fixed the about section to be responsive for all sizes

src/Components/About/About.css
Hey @MastanSayyad @Priyaaa1 
issue closes #719 
I have made the About us responsive for all screen sizes Except 768px
please have a look - 
Uploading starconnect responsive.mp4…
=> ✔️Made AbouUs Page responsive
